### ISSUE TITLE
maxscript direct connect ?

### ISSUE THREAD

**Issue by imgestudyo** [Alhadis/language-maxscript#5]
can you make video  please how to use atom with maxscript directly  ? 

your package is the same way  ? 

https://www.youtube.com/watch?v=1P6wvSiykTQ

**Comment by Alhadis** [comment]
There's a beginner's guide to Atom here:

https://flight-manual.atom.io/

I'm not adding video tutorials because most Atom users know how to install and use a package.

**Comment by imgestudyo** [comment]
but how to connect execute same time 3ds max this is possible ?

 Saygılarımızla...



*© Imge Studyo Animasyon Ltd. Şti.*

**Comment by Alhadis** [comment]
No, it's not possible. I no longer have access to 3DS Max either, so I'm afraid it's impossible for me to implement at this point.

Sorry.
